version: "3.8"

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./signal-cli-config:/home/.local/share/signal-cli
    environment:
      MODE: json-rpc
    restart: unless-stopped

  bot:
    build: .
    depends_on:
      - signal-cli-rest-api
    environment:
      SIGNAL_SERVICE: http://signal-cli-rest-api:8080
      PHONE_NUMBER: ${PHONE_NUMBER} # Replace with your Signal bot's phone number
    restart: unless-stopped