version: "3.8"

services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./signal-cli-config:/home/.local/share/signal-cli
    environment:
      MODE: json-rpc
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/about"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  bot:
    build: .
    depends_on:
      signal-cli-rest-api:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./signal-cli-config:/home/.local/share/signal-cli
      - ./signal-ai-data:/root/.signal-ai
    restart: unless-stopped

volumes:
  redis-data:
